add_executable(moo_placeholder_test placeholder_test.cpp)
target_link_libraries(moo_placeholder_test PRIVATE moo_core)
add_test(NAME moo_placeholder COMMAND moo_placeholder_test)

add_executable(moo_incremental_schedule_test incremental_schedule_test.cpp)
target_link_libraries(moo_incremental_schedule_test PRIVATE moo_core)
add_test(NAME moo_incremental_schedule COMMAND moo_incremental_schedule_test)
